# Site settings
title: Lucas Andrey
email: andreybleme1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Bem vindo! Esse blog foi criado para compartilhar 
 conhecimentos relacionados a desenvolvimento de software e afins :)
baseurl: "" # the subpath of your site, e.g. /blog/
meta-description: Bem vindo! Esse blog foi criado para compartilhar conhecimentos relacionados a desenvolvimento de software e afins :)
url: "http://andreybleme.com" # the base hostname & protocol for your site
twitter_username: andreybleme
github_username:  andreybleme
linkedin_username: pub/lucas-andrey/96/319/b2

# Build settings
markdown: kramdown